#ifdef SPANISH
	#define STR0001 "<!doctype html>"
#else
	#ifdef ENGLISH
		#define STR0001 "<!doctype html>"
	#else
		// DETALHES DO LAYOUT
#define STR0001 "<!doctype html>"
#define STR0002 "<html><head>"
#define STR0003 "<meta charset='utf-8'>"
#define STR0004 "<title>Workflor - Pedido de Venda</title>"
#define STR0005 "	<style>"
#define STR0006 "		@import url(https://fonts.googleapis.com/css?family=Roboto:300); /*Calling our web font*/"
#define STR0007 ""
#define STR0008 "        /* Some resets and issue fixes */"
#define STR0009 "        #outlook a { padding:0; }"
#define STR0010 "        body{ width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0; }     "
#define STR0011 "        .ReadMsgBody { width: 100%; }"
#define STR0012 "        .ExternalClass {"
#define STR0013 "	width: 100%;"
#define STR0014 "	background-color: #EEFCFF;"
#define STR0015 "	border: medium solid #EBEBEB;"
#define STR0016 "} "
#define STR0017 "        .backgroundTable {margin:0 auto; padding:0; width:100%;!important;} "
#define STR0018 "        table td {border-collapse: collapse;}"
#define STR0019 "        .ExternalClass * {line-height: 115%;}"
#define STR0020 "        /* End reset */"
#define STR0021 "        "
#define STR0022 "        /* These are our tablet/medium screen media queries */"
#define STR0023 "        @media screen and (max-width: 630px){"
#define STR0024 "			/* Display block allows us to stack elements */"
#define STR0025 "            *[class="mobile-column"] {display: block;} "
#define STR0026 "            "
#define STR0027 "            /* Some more stacking elements */"
#define STR0028 "            *[class="mob-column"] {float: none !important;width: 100% !important;}     "
#define STR0029 "                 "
#define STR0030 "            /* Hide stuff */"
#define STR0031 "            *[class="hide"] {display:none !important;}          "
#define STR0032 "            "
#define STR0033 "            /* This sets elements to 100% width and fixes the height issues too, a god send */"
#define STR0034 "            *[class="100p"] {width:100% !important; height:auto !important;}                    "
#define STR0035 "                "
#define STR0036 "            /* For the 2x2 stack */            "
#define STR0037 "            *[class="condensed"] {padding-bottom:40px !important; display: block;}"
#define STR0038 "            "
#define STR0039 "            /* Centers content on mobile */"
#define STR0040 "            *[class="center"] {text-align:center !important; width:100% !important; height:auto !important;}            "
#define STR0041 "            "
#define STR0042 "            /* 100percent width section with 20px padding */"
#define STR0043 "            *[class="100pad"] {width:100% !important; padding:20px;} "
#define STR0044 "            "
#define STR0045 "            /* 100percent width section with 20px padding left & right */"
#define STR0046 "            *[class="100padleftright"] {width:100% !important; padding:0 20px 0 20px;} "
#define STR0047 "            "
#define STR0048 "            /* 100percent width section with 20px padding top & bottom */"
#define STR0049 "            *[class="100padtopbottom"] {width:100% !important; padding:20px 0px 20px 0px;} "
#define STR0050 "        }"
#define STR0051 "    </style>"
#define STR0052 "	"
#define STR0053 "	<div style="background:#ffffff;"></div>"
#define STR0054 "</head>"
#define STR0055 ""
#define STR0056 "<body style="padding:0; margin:0" bgcolor="#ffffff">"
#define STR0057 "	<table border="0" cellpadding="0" cellspacing="0" style="margin: 0; padding: 0" width="100%">"
#define STR0058 "		<td align="center" width="50%" style="font-size:14px; color:#848484;"><font face="'Roboto', Arial, sans-serif">Este é um e-mail automático. Não é necessário respondê-lo.</font></td>"
#define STR0059 "	    <tr>"
#define STR0060 "	        <td align="center" valign="top">"
#define STR0061 "			    <table width="640" border="0" cellspacing="0" cellpadding="0" class="hide">"
#define STR0062 "                	<tr>"
#define STR0063 "                    	<td height="20"></td>"
#define STR0064 "                	</tr>"
#define STR0065 "            	</table>"
#define STR0066 "            	<table width="640" cellspacing="0" cellpadding="0" bgcolor="#" class="100p">"
#define STR0067 "	                <tr>"
#define STR0068 "	                    <td bgcolor="#6A3735" width="640" valign="top" class="100p">"
#define STR0069 "    	                    <div>"
#define STR0070 "        						<table width="640" border="0" cellspacing="0" cellpadding="20" class="100p">"
#define STR0071 "									<tr>"
#define STR0072 "										<td valign="top">"
#define STR0073 "											<table border="0" cellspacing="0" cellpadding="0" width="600" class="100p">"
#define STR0074 "												<tr>"
#define STR0075 "                                                    <td align="center" width="50%" class="100p"><a href="http://www.astralpaes.com.br/" target="_blank"><img src="http://www.astralpaes.com.br/Workflow/logo_astral.png" width="200" height="96" /></a>"
#define STR0076 "													</td>"
#define STR0077 "												</tr>"
#define STR0078 "                                            </table>"
#define STR0079 "                                            "
#define STR0080 "											<table border="0" cellspacing="0" cellpadding="0" width="600" class="100p">"
#define STR0081 "                                                <tr>"
#define STR0082 "                                                    <td height="35"></td>"
#define STR0083 "                                                </tr>"
#define STR0084 "                                                <tr>"
#define STR0085 "                                                    <td align="center" style="color:#FFFFFF; font-size:24px;">"
#define STR0086 "                                                        <font face="'Roboto', Arial, sans-serif">"
#define STR0087 "															<span style="font-size:30px;">PEDIDO RECEBIDO COM SUCESSO!</span>"
#define STR0088 "															<br/><br/>"
// CLIENTE INICIO
#define STR0089 "															<span style="font-size:20px;">Prezado(a) Sr.(a) ASTRAL INDUSTRIA E COMERCIO DE PAES</span><br/><br/>"
// CLIENTE FIM
#define STR0090 "															<span style="font-size:16px;">Informamos que o pedido abaixo foi recebido com sucesso pelo nosso sistema. A liberação de sua(s) compra(s) está condicionada à aprovação de crédito junto à instituição financeira e o prazo de entrega começa a contar a partir desta aprovação.</span>"
#define STR0091 "														</font>"
#define STR0092 "                                                    </td>"
#define STR0093 "                                                </tr>"
#define STR0094 "                                                <tr>"
#define STR0095 "                                                    <td height="35"></td>"
#define STR0096 "                                                </tr>"
#define STR0097 "                                            </table>"
#define STR0098 "                                        </td>"
#define STR0099 "                                    </tr>"
#define STR0100 "                                </table>"
#define STR0101 "                            </div>"
#define STR0102 "						</td>"
#define STR0103 "					</tr>"
#define STR0104 "				</table>"
#define STR0105 "				<table width="640" border="0" cellspacing="0" cellpadding="20" bgcolor="#FFAFAC" class="100p">"
#define STR0106 "					<tr>"
// N�MERO DO PEDIDO INICIO
#define STR0107 "						<td align="center" style="font-size:24px; color:#424242;"><font face="'Roboto', Arial, sans-serif">Detalhes do seu Pedido: <b>113658</b></font></td>"
// N�MERO DO PEDIDO FIM
#define STR0108 "					</tr>"
#define STR0109 "					<tr>"
#define STR0110 "						<td align="center" style="font-size: 16px; color: #F5CCCA;"><table width="100%" border="1" align="center" cellpadding="3" cellspacing="0" >"
#define STR0111 "					      <tbody>"
#define STR0112 "						      <tr style="font-family: 'Roboto', Arial, 'sans-serif'; color: #FFFFFF; font-size: 14px">"
#define STR0113 "						        <td width="16%" align="center" valign="middle" bgcolor="#6A3735"><p><b>Codigo</b></p></td>"
#define STR0114 "						        <td width="41%" align="center" valign="middle" bgcolor="#6A3735"><p><b>Descrição</b></p></td>"
#define STR0115 "						        <td width="12%" align="center" valign="middle" bgcolor="#6A3735"><p><b>Qtd.</b></p></td>"
#define STR0116 "						        <td width="16%" align="center" valign="middle" bgcolor="#6A3735"><p><b>Vl. Unit.</b></p></td>"
#define STR0117 "						        <td width="15%" align="center" valign="middle" bgcolor="#6A3735"><p><b>Vl. Total</b></p></td>"
// PRODUTOS INICIO
#define STR0118 "					          </tr>"
#define STR0119 "						      <tr bgcolor="#FFFFFF" style="font-family: 'Roboto', Arial, 'sans-serif'; color: #000000; font-size: 13px">"
#define STR0120 "						        <td>PAE0001</td>"
#define STR0121 "						        <td>PAO HAMBURGUER 120 G</td>"
#define STR0122 "						        <td>10</td>"
#define STR0123 "						        <td>3,59</td>"
#define STR0124 "						        <td>35,90</td>"
#define STR0125 "					          </tr>"
#define STR0126 "						      <tr bgcolor="#FFFFFF" style="font-family: 'Roboto', Arial, 'sans-serif'; color: #000000; font-size: 13px">"
#define STR0127 "						        <td>PAE0002</td>"
#define STR0128 "						        <td>PAO GERG. 720G ASTRAL</td>"
#define STR0129 "						        <td>1</td>"
#define STR0130 "						        <td>4</td>"
#define STR0131 "						        <td>4</td>"
#define STR0132 "					          </tr>"
#define STR0133 "						      <tr bgcolor="#FFFFFF" style="font-family: 'Roboto', Arial, 'sans-serif'; color: #000000; font-size: 13px">"
#define STR0134 "						        <td>CON0127</td>"
#define STR0135 "						        <td>BACON EM CUBOS</td>"
#define STR0136 "						        <td>7</td>"
#define STR0137 "						        <td>2</td>"
#define STR0138 "						        <td>14</td>"
#define STR0139 "					          </tr>"
#define STR0140 "						      <tr bgcolor="#FFFFFF" style="font-family: 'Roboto', Arial, 'sans-serif'; color: #000000; font-size: 13px">"
#define STR0141 "						        <td>FRI0017</td>"
#define STR0142 "						        <td>FRANGO DESFIADO SAUDALI</td>"
#define STR0143 "						        <td>2</td>"
#define STR0144 "						        <td>2</td>"
#define STR0145 "						        <td>4</td>"
#define STR0146 "					          </tr>"
// PRODUTOS FIM
#define STR0147 "				          </tbody>"
#define STR0148 "					      </table>"
#define STR0149 "						  <table width="100%" border="1" bgcolor="#FFFFFF" cellpadding="3" cellspacing="0" >"
#define STR0150 "						    <tbody style="font-family: 'Roboto', Arial, 'sans-serif'; color: #000000; font-size: 13px">"
#define STR0151 "						      <tr bgcolor="#6A3735" style="font-family: 'Roboto', Arial, 'sans-serif'; color: #FFFFFF; font-size: 13px">"
#define STR0152 "						        <td width="23%">(+) SubTotal</td>"
#define STR0153 "						        <td width="23%">(-) Desconto</td>"
#define STR0154 "						        <td width="23%">(+) Valor ST</td>"
#define STR0155 "						        <td width="31%">(=) Valor Total</td>"
#define STR0156 "					          </tr>"
#define STR0157 "						      <tr>"
// TOTAIS INICIO
#define STR0158 "						        <td>310,65</td>"
#define STR0159 "						        <td>0,00</td>"
#define STR0160 "						        <td>5,43</td>"
#define STR0161 "						        <td>316,08</td>"
// TOTAIS FIM
#define STR0162 "					          </tr>"
#define STR0163 "					        </tbody>"
#define STR0164 "				      	  </table>"
#define STR0165 "						</td>"
#define STR0166 "					</tr>"
#define STR0167 "				</table>"
#define STR0168 "				<table width="640" border="0" cellspacing="0" cellpadding="20" bgcolor="#6A3735" class="100p">"
#define STR0169 "					<tr>"
#define STR0170 "						<td align="center" style="font-size:16px; color:#ffffff;"><font face="'Roboto', Arial, sans-serif"><span style="font-size:24px;">ENDEREÇO DE ENTREGA</span><br /><br />"
// ENFERE�O INICIO
#define STR0171 "							<span style="font-size:16px;">Rua Bernardo Alves Costa 671, Bairro São Geraldo, Sete Lagoas MG.</span></font>"
// ENDERE�O FIM
#define STR0172 "						</td>"
#define STR0173 "					</tr>"
#define STR0174 "				</table>"
#define STR0175 "				<table width="640" border="0" cellspacing="0" cellpadding="20" bgcolor="#ffffff" class="100p">"
#define STR0176 "					<tr>"
#define STR0177 "						<td align="center" width="50%" style="font-size:18px; color:#868282;"><font face="'Roboto', Arial, sans-serif"><b>INFORMAÇÕES IMPORTANTES:</b></font></td>"
#define STR0178 "					</tr>"
#define STR0179 "				</table>"
#define STR0180 "				<table width="640" border="0" cellspacing="0" cellpadding="20" bgcolor="#ffffff" class="100p">"
#define STR0181 "					<tr>"
#define STR0182 "						<td align="left" width="50%" style="font-size:14px; color:#848484;">"
#define STR0183 "							<font face="'Roboto', Arial, sans-serif">"
#define STR0184 "								<p>Confira os seus dados cadastrais.</p>"
#define STR0185 "								<p>Nossas entregas são feitas de segunda à sexta-feira, das 08 às 21h, exceto feriados locais e nacionais.</p>"
#define STR0186 "								<p>Os produtos são perecíveis e, portanto, é necessário um local adequado para o seu armazenamento.</p>"
#define STR0187 "								<p>Não entregamos em locais de difícil acesso e nem em locais sem estacionamento, pois os caminhões precisam de um tempo de permanência para realizar as entregas.</p>"
#define STR0188 "								<p>É de total responsabilidade do Cliente qualquer necessidade de armazenamento após a entrega. Se o produto recebido permanecer em um local não adequado, sua qualidade poderá ficar comprometida.</p>"
#define STR0189 "								<p>O prazo de entrega pode ser alterado devido a não formação de carga para a região em questão. Caso ocorra, a entrega será automaticamente agrupada em um próximo carregamento.</p>"
#define STR0190 "								<p>O atendimento funciona de segunda à sexta, das 08 às 18h, exceto feriados nacionais.</p>"
#define STR0191 "								<p>As entregas não são realizadas para endereços diferentes do definido pelo cliente no ato do fechamento do pedido, como vizinhos, por exemplo. Ao confirmar o pedido, o comprador estará, automaticamente, autorizando a entrega da mercadoria a porteiros, recepcionistas, secretárias e familiares, desde que assinem o protocolo de entrega e apresentem documento de identificação.</p>"
#define STR0192 "								<p>O recebimento dos produtos importa em reconhecimento das suas perfeitas condições, aptos para venda e consumo, inclusive no que tange ao prazo de validade, peso apresentado e integridade das embalagens.</p>"
#define STR0193 "							</font>"
#define STR0194 "						</td>"
#define STR0195 "					</tr>"
#define STR0196 "				</table>"
#define STR0197 "				<table width="640" border="0" cellspacing="0" cellpadding="20" bgcolor="#ffffff" class="100p">"
#define STR0198 "					<tr>"
#define STR0199 "						<td align="center" style="font-size: 16px; color: #FFFFFF;"><p><font face="'Roboto', Arial, sans-serif"><span style="color:#2a8e9d; font-size:24px;">Tudo fica mais gostoso quando o pão é Astral!</span></font></p>"
#define STR0200 "						</td>"
#define STR0201 "						<td align="right" width="50%" style="font-size:14px; color:#848484;">"
#define STR0202 "							<div align="center"> <a href="https://www.instagram.com/astralpaes/" target="_blank"><img src="http://www.astralpaes.com.br/Workflow/instagram.jpg" width="30" height="30" /></a>&nbsp;"
#define STR0203 "								<a href="https://pt-br.facebook.com/astralpaes" target="_blank"><img src="http://www.astralpaes.com.br/Workflow/facebook.jpg" width="30" height="30"/></a>"
#define STR0204 "							</div>"
#define STR0205 "						</td>"
#define STR0206 "					</tr>"
#define STR0207 "				</table>"
#define STR0208 "			</td>"
#define STR0209 "		</tr>"
#define STR0210 "	</table>"
#define STR0211 "</body>"
#define STR0212 "</html>"
	#endif
#endif